[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
depining = "H5bdVxHZQ7m9jELoocVRAjvBzS9D4i5hJNNSc8G58yDx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test-anchor = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/depining.ts"
test-litesvm = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/depining_litesvm.ts"
test-anchorlitesvm = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/depining_anchorlitesvm.ts"